/*
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amplifyframework.testutils.model;

import androidx.core.util.ObjectsCompat;

import com.amplifyframework.core.model.Model;
import com.amplifyframework.core.model.annotations.BelongsTo;
import com.amplifyframework.core.model.annotations.Index;
import com.amplifyframework.core.model.annotations.ModelConfig;
import com.amplifyframework.core.model.annotations.ModelField;

import java.util.UUID;

/**
 * An example of a class that would be generated by Amplify Codegen.
 */
@ModelConfig(targetName = "Car")
@Index(fields = {"vehicleModel"}, name = "modelBasedIndex")
public final class Car implements Model {

    @ModelField(targetName = "id", targetType = "ID", isRequired = true)
    private String id;

    @ModelField(targetName = "vehicle_model", targetType = "String", isRequired = true)
    private String vehicleModel;

    @BelongsTo(targetType = "Person")
    @ModelField(targetName = "personId", targetType = "ID", isRequired = true)
    private String personId;

    /**
     * Default constructor.
     */
    public Car() {
        super();
    }

    private Car(String uniqueId,
                String vehicleModel,
                String personId) {
        this.id = uniqueId;
        this.vehicleModel = vehicleModel;
        this.personId = personId;
    }

    /**
     * Returns an instance of the builder.
     * @return an instance of the builder.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Returns Id.
     * @return Id.
     */
    public String getId() {
        return id;
    }

    /**
     * Return the vehicle model.
     * @return the vehicle model.
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * Return the person Id.
     * @return the person Id.
     */
    public String getPersonId() {
        return personId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Car)) {
            return false;
        }
        Car car = (Car) obj;
        return ObjectsCompat.equals(getId(), car.getId()) &&
                ObjectsCompat.equals(getVehicleModel(), car.getVehicleModel()) &&
                ObjectsCompat.equals(getPersonId(), car.getPersonId());
    }

    @Override
    public int hashCode() {
        return ObjectsCompat.hash(
                getId(),
                getVehicleModel(),
                getPersonId());
    }

    @Override
    public String toString() {
        return "Car{" +
                "id='" + id + '\'' +
                ", vehicleModel='" + vehicleModel + '\'' +
                ", personId=" + personId +
                '}';
    }

    /**
     * Interface for vehicle model step.
     */
    public interface VehicleModelStep {
        /**
         * Set the vehicle model.
         * @param vehicleModel vehicle model.
         * @return next step.
         */
        PersonIdStep vehicleModel(String vehicleModel);
    }

    /**
     * Interface for personId step.
     */
    public interface PersonIdStep {
        /**
         * Set the person Id.
         * @param personId person Id.
         * @return next step.
         */
        FinalStep personId(String personId);
    }

    /**
     * Interface for final step.
     */
    public interface FinalStep {
        /**
         * Returns the built Car object.
         * @return the built Car object.
         */
        Car build();
    }

    /**
     * Builder to build the Person object.
     */
    public static final class Builder implements
            VehicleModelStep, PersonIdStep, FinalStep {
        private String vehicleModel;
        private String personId;

        /**
         * Set the vehicle model and proceed to PersonStep.
         * @param vehicleModel vehicle model
         * @return next step
         */
        public PersonIdStep vehicleModel(String vehicleModel) {
            this.vehicleModel = vehicleModel;
            return this;
        }

        /**
         * Set the person Id and proceed to FinalStep.
         * @param personId person Id
         * @return next step
         */
        public FinalStep personId(String personId) {
            this.personId = personId;
            return this;
        }

        /**
         * Returns the builder object.
         * @return the builder object.
         */
        public Car build() {
            return new Car(
                    UUID.randomUUID().toString(),
                    vehicleModel,
                    personId);
        }
    }
}
