version: 0.2
# This file is used as part of the build process implemented using AWS CodeBuild [1].
# The CodeBuild documentation [2] provides an introduction of the service and its capabilities. In general
# terms, it allows us to configure the actions executed when a build is triggered by a commit to the
# amplify-android GitHub repository.
#
# For the purposes of this repo, we're simply running a build by using "./gradlew build"
# command and in the post-build phase, we consolidate the JUnit report files in one location.
# In the reports section, we're instructing CodeBuild to publish those reports which can be
# viewed in the AWS CodeBuild console (Future work will be to publish those to Github for easier access).
#
# [1] - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# [2] - https://docs.aws.amazon.com/codebuild/latest/userguide/planning.html
env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      java: corretto8
      android: 29
    commands:
      - echo 'Install phase starting'
      - export APP_ID="`aws amplify list-apps --output text --query \"apps[?name == 'InstrumentedTests'].appId\"`"
      - npm install -g @aws-amplify/cli
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
      - >
        amplify pull \
            --amplify "{\"projectName\":\"InstrumentedTestsBackend\",\"appId\":\"$APP_ID\",\"envName\":\"main\",\"defaultEditor\":\"code\"}" \
            --frontend "{\"frontend\":\"android\",\"config\":{\"ResDir\":\"aws-datastore/src/androidTest/res\"}}" \
            --providers "{\"awscloudformation\":{\"configLevel\":\"general\",\"useProfile\":false,\"region\":\"us-east-1\"}}" --yes \
            --yes
      - >
        targets=("core/src/androidTest/res" "aws-analytics-pinpoint/src/androidTest/res" "aws-api/src/androidTest/res" "aws-predictions/src/androidTest/res" "aws-storage-s3/src/androidTest/res")
          start_index=1
          number_of_targets=${#targets[@]}
          end_index=$(($number_of_targets))

          for target_dir in "${targets[@]}"
          do
            echo "Copying config files to $target_dir "
            mkdir -p "$target_dir"
            cp -R aws-datastore/src/androidTest/res/* $target_dir
          done
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting'
      - JAVA_HOME=$JDK_8_HOME ./gradlew build
      - JAVA_HOME=$JDK_8_HOME ./gradlew assembleAndroidTest
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
      - pwd
      - mkdir -p allTests
      - cp -f ./*/build/reports/tests/testDebugUnitTest/*.xml ./allTests
    finally:
      - echo 'Post-build phase completed.'
reports:
  amplify-android-unit-tests:
    files:
      - allTests/*
    discard-paths: yes
    file-format: JUNITXML
artifacts:
  files:
    - '**/*.apk'
  name: AmplifyAndroidCatApks
  discard-paths: yes