coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
    patch:
      default:
        target: auto
        threshold: 0%
comment:
  layout: diff
  behavior: default
  require_changes: false
