/*
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amplifyframework.hub;

import com.amplifyframework.core.async.AmplifyOperationContext;

public class HubPayload {

    /**
     * The name, tag, or grouping of the HubPayload. Recommended to be a small string without spaces,
     * such as `signIn` or `hang_up`. For AmplifyOperations, this will be a concatenation of the category display name
     * and a short name of the operation type, as in "Storage.getURL" or "Storage.downloadFile".
     */
    private String eventName;

    /**
     * A structure used to pass the source, or context, of the HubPayload. For HubPayloads that are
     * generated from AmplifyOperations, this field will be the Operation's associated AmplifyOperationContext.
     */
    public AmplifyOperationContext context;

    /**
     * A free-form structure used to pass objects or custom data. For HubPayloads that are generated from
     * AmplifyOperations, this field will be the Operation's associated AsyncEvent.
     */
    public Object data;

    /**
     * Default constructor
     */
    public HubPayload() {

    }

    /**
     * Construct a Hub payload.
     *
     * @param eventName name that identifies the event passed through Hub
     * @param context context that includes the request and other metadata about the operation
     *                that generated the event with this payload
     * @param data the data of the event generated by the operation
     */
    public HubPayload(String eventName, AmplifyOperationContext context, Object data) {
        this.eventName = eventName;
        this.context = context;
        this.data = data;
    }

    public String getEventName() {
        return eventName;
    }

    public HubPayload eventName(String eventName) {
        this.eventName = eventName;
        return this;
    }

    public AmplifyOperationContext getContext() {
        return context;
    }

    public HubPayload context(AmplifyOperationContext context) {
        this.context = context;
        return this;
    }

    public Object getData() {
        return data;
    }

    public HubPayload data(Object data) {
        this.data = data;
        return this;
    }
}
