/*
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amplifyframework.hub;

import java.util.UUID;

/**
 * A payload is the top-level data envelope that gets passed around on the Hub.
 * Payloads are published onto the hub, and listeners subscribe to the hub to
 * receive payloads.
 */
public final class HubPayload {
    private final String eventName;
    private final Object eventData;
    private final UUID payloadId;

    /**
     * Construct a Hub payload that has no event data.
     * @param eventName the name of the event generated by the operation
     */
    public HubPayload(String eventName) {
        this(eventName, null);
    }

    /**
     * Construct a Hub payload.
     * @param eventName The name of this event
     * @param eventData The data of the event generated by the operation
     */
    public HubPayload(String eventName, Object eventData) {
        this.eventName = eventName;
        this.eventData = eventData;
        this.payloadId = UUID.randomUUID();
    }

    /**
     * Gets the name, tag, or grouping of the HubPayload. Recommended to be a small string without spaces,
     * such as `signIn` or `hang_up`. For AmplifyOperations, this will be a concatenation of the
     * category display name and a short name of the operation type, as in "Storage.getURL" or
     * "Storage.downloadFile".
     * @return Event name
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Gets a free-form structure used to pass objects or custom data. For HubPayloads that are generated
     * from AmplifyOperations, this field will be the Operation's associated AsyncEvent.
     * @return Event data
     */
    public Object getEventData() {
        return eventData;
    }

    /**
     * Gets a unique identifier that identifies the payload.
     * @return Unique ID for this payload
     */
    public UUID getPayloadId() {
        return payloadId;
    }

    @Override
    public String toString() {
        return "HubPayload{" +
                "eventName='" + eventName + '\'' +
                ", eventData=" + eventData.toString() +
                ", payloadId =" + payloadId.toString() +
                '}';
    }

    @Override
    public boolean equals(Object thatObject) {
        if (this == thatObject) {
            return true;
        }
        if (!(thatObject instanceof HubPayload)) {
            return false;
        }
        HubPayload that = (HubPayload) thatObject;
        return getPayloadId().equals(that.getPayloadId());
    }

    @Override
    public int hashCode() {
        return getPayloadId().hashCode();
    }
}

