#!/bin/bash

set -x
set -e

# In your ~/.aws/config and ~/.aws/credentials, we expect this profile
# It must have S3 read-only access to the config bucket.
readonly cli_profile='amplify_sdk_test'

# This bucket contains a collection of config files that are used by the
# integration tests. They contain sensitive
# tokens/credentials/identifiers, so are not published publicly.
readonly config_bucket='amplify-circleci-android-payload'

# Mac OS X's antiquated version of bash doesn't have associative arrays.
# So, use two simple arrays and join on index.
# sources are remote URLs, targets are local file paths
readonly sources=(
    "s3://$config_bucket/awsconfiguration-analytics.json"
    "s3://$config_bucket/awsconfiguration-api.json"
    "s3://$config_bucket/amplifyconfiguration-analytics.json"
    "s3://$config_bucket/amplifyconfiguration-core.json"
    "s3://$config_bucket/amplifyconfiguration-api.json"
    "s3://$config_bucket/amplifyconfiguration-datastore.json"
)
readonly targets=(
    "aws-analytics-pinpoint/src/androidTest/res/raw/awsconfiguration.json"
    "aws-api/src/androidTest/res/raw/awsconfiguration.json"
    "aws-analytics-pinpoint/src/androidTest/res/raw/amplifyconfiguration.json"
    "core/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-api/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-datastore/src/androidTest/res/raw/amplifyconfiguration.json"
)

# Compute indices into the arrays.
readonly start_index=0
readonly source_array_size=${#sources[@]}
readonly end_index=$(($source_array_size - 1))

# Iterate source and target, coying out of s3 to local path.
for index in $(seq $start_index $end_index); do
    aws --profile "$cli_profile" \
        s3 cp \
        "${sources[$index]}" \
        "${targets[$index]}"
done

