package com.amplifyframework.statemachine

/**
 * Use data/enum classes to implement since member function implementation
 * is auto generated by data/enum classes.
 */
interface State {
    val type: String
        get() = this.toString()

    override fun equals(other: Any?): Boolean
    override fun toString(): String
    override fun hashCode(): Int
}
