RELEASE_TAG_PREFIX = 'release_v'
default_platform(:android)

platform :android do |options|
  gradle_properties_path = File.expand_path("#{Dir.pwd()}/../../gradle.properties")
  gradle_project_root = File.dirname(gradle_properties_path)
  version_regex = /(\d*)\.(\d*)\.(\d*)(?:-unstable\.)?(\d*)?/

  desc "Create a pre-release version by pushing a tag to GitHub, and publishing to Maven"
  before_all do 
    # Perform a fetch before inferring the next version 
    # to reduce race conditions with simultaneous pipelines attempting to create the same tag
    sh('git', 'fetch', '--tags')
    sh('git', 'fetch')
  end

  lane :unstable do
    latest_tag = last_git_tag(pattern: "#{RELEASE_TAG_PREFIX}*")

    UI.message("Last version #{latest_tag}")
    next_version = calculate_next_canary_version(prerelease_identifier: 'unstable', 
                                                release_tag_prefix: RELEASE_TAG_PREFIX,
                                                from_tag: latest_tag )
    UI.message("Next version: #{next_version}")

    # Update version information in gradle.properties
    update_gradle_properties(version: next_version)

    gradle(
      project_dir: gradle_project_root,
      task: "build"
    )

    # Create tag and push to origin
    add_tag(version: RELEASE_TAG_PREFIX + next_version.to_s)

    # # Push to maven
    UI.message("Pushing #{next_version.to_s} to maven")
    publish_to_maven
  end

  desc "Create a release version by building and committing a changelog, pushing a tag to GitHub, and publishing to Maven"  
  lane :release do |options|
    # Exclude unstable release tags
    latest_tag = last_git_tag(pattern: "#{RELEASE_TAG_PREFIX}*[0-9].*[0-9].*[0-9][!*]")
    UI.message("Last version #{latest_tag.gsub(RELEASE_TAG_PREFIX,"")}")
    next_version, commits = calculate_next_release_version(release_tag_prefix: RELEASE_TAG_PREFIX, 
                                                          from_tag: latest_tag)

    UI.message("Calculated next release version: #{next_version}")
    if !options[:next_version].nil?
      UI.message("Using version override: #{options[:next_version]}")
      next_version = options[:next_version]
    end
    
    UI.message("Releasing version: #{next_version}")
    release_tag = RELEASE_TAG_PREFIX + next_version.to_s
    update_gradle_properties(version: next_version)
    sh("git", "add", gradle_properties_path)

    # Leaving these commented out for now
    # changelog = changelog_from_git_commits(between: [latest_tag,'HEAD'])
    # write_changelog(changelog: changelog, path: 'CHANGELOG.md')

    # Commit and push 
    release_commit(version: next_version)

    # Create tag and push to origin
    add_tag(version: release_tag)
    
    # Push to maven
    UI.message("Pushing release #{next_version.to_s} to maven")
    push_tag_to_maven(release_tag: release_tag)
  end

  desc "Checks out a tag and runs the uploadArchives gradle task."
  lane :push_tag_to_maven do |options|
    UI.message("Pushing release #{options[:release_tag]} to maven")
    sh("git", "checkout", options[:release_tag])
    publish_to_maven
  end

  desc "Increment versions"
  private_lane :update_gradle_properties do |options|
    version = options[:version].to_s
    segments = version.match(version_regex).captures # version.split('.')
    prerelease = segments.length() > 3 ?  0 : segments[-1].to_i

    # Derive the version code from version segements and pre-release number (if applicable)
    version_code = segments[0].to_i * 100000 + segments[1].to_i * 1000 + segments[2].to_i * 10 + prerelease

    UI.message("Updating versionName and versionCode in gradle.properties")

    set_key_value(file: gradle_properties_path, key: 'VERSION_NAME', value: version)
    set_key_value(file: gradle_properties_path, key: 'VERSION_CODE', value: version_code.to_s)

  end

  desc "Create the release commit."
  private_lane :release_commit do |options|
    next_version = options[:version]
    commit_message = "chore: release #{next_version} [skip ci]"
    sh('git', 'commit', '-am', commit_message)
  end

  desc "Tag in git and push to GitHub"
  private_lane :add_tag do |options|
    next_version = options[:version]

    add_git_tag(tag: next_version)
    push_git_tags(tag: next_version)
  end

  desc "Publish release to maven using attributes from environment variables."
  private_lane :publish_to_maven do |options|
    gradle(
      project_dir: gradle_project_root,
      task: "uploadArchives",
      print_command: false,
      flags: '--stacktrace',
      properties: {
        "SONATYPE_NEXUS_USERNAME": ConfigValueReader.from_environment_variable('SONATYPE_NEXUS_USERNAME'),
        "SONATYPE_NEXUS_PASSWORD": ConfigValueReader.from_environment_variable('SONATYPE_NEXUS_PASSWORD'),
        "signing.inMemoryKey": ConfigValueReader.from_environment_variable('signing.inMemoryKey'),
        "signing.password": ConfigValueReader.from_environment_variable('signing.password'),
        "signing.keyId": ConfigValueReader.from_environment_variable('signing.keyId'),
        "signing.secretKeyRingFile": ConfigValueReader.from_environment_variable('signing.secretKeyRingFile')
      }
    )
  end

  desc "Publish release to maven without overriding gradle properties."
  private_lane :publish_to_maven_no_overrides do |options|
    gradle(
      project_dir: gradle_project_root,
      task: "uploadArchives",
      print_command: false,
      flags: '--stacktrace'
    )
  end

  desc "Retrieve a parameter value from SSM."
  private_lane :get_param_value do |options|
    sh(
      command: "aws ssm get-parameter --name #{options[:param_name]} --with-decryption --region us-east-1 --query Parameter.Value --output text",
      log: false
    )
  end

  desc "Cleanup all the build artifacts"
  private_lane :cleanup do |options|
    gradle(
      project_dir: gradle_project_root,
      task: "clean"
    )
  end
end

module ConfigValueReader
  def self.from_environment_variable(param_name)
    ENV[param_name.gsub('.','_')]
  end

  def self.from_ssm(param_name)
    result = `aws ssm get-parameter --name #{param_name} --with-decryption --region us-east-1 --query Parameter.Value --output text`
    if $?.exitstatus != 0
      raise "Failed to get value for parameter #{param_name}"
    end
    result
  end
end
