default_platform(:android)

import_from_git(
    url: 'https://github.com/aws-amplify/amplify-ci-support',
    branch: 'android/fastlane-actions',
    path: './src/fastlane/release_actions/fastlane/AndroidAppsFastfile'
)

# When testing against local changes, comment out the above and use the line below instead.
# import '~/github/aws-amplify/amplify-ci-support/src/fastlane/release_actions/fastlane/AndroidAppsFastfile'

platform :android do |options|
  override_lane :build_parameters do
    project_root = File.expand_path("#{Dir.pwd()}/../..")
    UI.message("Building version groups for amplify-android from #{project_root}")
    {
      repo: 'aws-amplify/amplify-android',
      product_name: 'Amplify Android',
      releases: [
        {
          release_tag_prefix: 'release_v',
          gradle_properties_path: "#{project_root}/gradle.properties",
          doc_files_to_update: ["#{project_root}/README.md", "#{project_root}/rxbindings/README.md"],
          release_title: 'Amplify Android',
          component_name: "AmplifyAndroid",
          changelog_path: "#{project_root}/CHANGELOG.md",
          changelog_ignore_scopes: ["Apollo", "apollo", "Events", "events", "release"]
        },
        {
          release_tag_prefix: 'release_apollo_v',
          gradle_properties_path: "#{project_root}/apollo/version.properties",
          doc_files_to_update: ["#{project_root}/apollo/README.md"],
          release_title: 'Apollo AppSync Extensions',
          component_name: "ApolloExtensions",
          changelog_path: "#{project_root}/apollo/CHANGELOG.md",
          changelog_include_scopes: ["Apollo", "apollo"]
        },
        {
          release_tag_prefix: 'release_events_v',
          gradle_properties_path: "#{project_root}/appsync/version.properties",
          doc_files_to_update: ["#{project_root}/appsync/README.md"],
          release_title: 'AWS AppSync Events for Android',
          component_name: "AppSyncEvents",
          changelog_path: "#{project_root}/appsync/CHANGELOG.md",
          changelog_include_scopes: ["Events", "events"]
        }
      ]
    }
  end
end
