# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Create a pre-release version by pushing a tag to GitHub, and pushing pods to CocoaPods"
  lane :unstable do 
    next_version = calculate_next_canary_version

    UI.message("Releasing unstable version: #{next_version}")

    # # Increment all specs and plists
    # increment_versions(version: next_version)

    # # Create tag and push to origin
    # add_tag(version: next_version)

    # # Push to maven
    # UI.message("Pushing unstable to maven")
  end

  desc "Create a release version by building and committing a changelog, pushing a tag to GitHub, and pushing pods to CocoaPods"  
  lane :release do
    next_version, commits = calculate_next_release_version

    UI.message("Releasing version: #{next_version}")

    # Increment all specs and plists
    # increment_versions(version: next_version)

    # changelog = build_changelog(version: next_version, commits: commits)

    # write_changelog(changelog: changelog, path: 'CHANGELOG.md')

    # Commit and push 
    # release_commit(version: next_version)

    # Create tag and push to origin
    # add_tag(version: next_version)

    # Push to maven
    # UI.message("Pushing release to maven")
  end
end
