version: 0.2
# This file is used as part of the build process implemented using AWS CodeBuild [1].
# The CodeBuild documentation [2] provides an introduction of the service and its capabilities. In general
# terms, it allows us to configure the actions executed when a build is triggered by a commit to the
# amplify-android GitHub repository.
#
# The CodeBuild project configuration in this file performs the following:
# - Copying integration test config files from a bucket OR using the amplify CLI to retrieve them from a set
#   of know projects.
# - Generates APK files for instrumented tests
#
# [1] - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# [2] - https://docs.aws.amazon.com/codebuild/latest/userguide/planning.html
env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      android: 29
      nodejs: 12
    commands:
      - echo 'Install phase starting'
      - npm install -g @aws-amplify/cli@4.30.0
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
      - |
        if [[ -z "${CONFIG_SOURCE_BUCKET}" ]]; then
          echo 'Pulling config files from Amplify'
          JAVA_HOME=$JDK_8_HOME ./gradlew pullBackendConfigFromAmplify
        else
          echo 'Pulling config files from S3'
          ./scripts/pull_backend_config_from_s3 ${CONFIG_SOURCE_BUCKET}
        fi
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting.'
      - JAVA_HOME=$JDK_8_HOME ./gradlew assembleAndroidTest
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
      - pwd
      - mkdir -p build/allTests
      - cp -f ./*/build/test-results/testDebugUnitTest/*.xml ./build/allTests
    finally:
      - echo 'Post-build phase completed.'
artifacts:
  files:
    - '**/*.apk'
  name: AmplifyAndroidCatApks
  discard-paths: yes