version: 0.2
# This file is used as part of the build process implemented using AWS CodeBuild [1].
# The CodeBuild documentation [2] provides an introduction of the service and its capabilities. In general
# terms, it allows us to configure the actions executed when a build is triggered by a commit to the
# amplify-android GitHub repository.
#
# For the purposes of this repo, we're simply running a build by using "./gradlew build"
# command and in the post-build phase, we consolidate the JUnit report files in one location.
# In the reports section, we're instructing CodeBuild to publish those reports which can be
# viewed in the AWS CodeBuild console (Future work will be to publish those to Github for easier access).
#
# [1] - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# [2] - https://docs.aws.amazon.com/codebuild/latest/userguide/planning.html
env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      android: 29
      nodejs: 12
      python: 3.8
    commands:
      - echo 'Install phase starting'
      - npm install -g xunit-viewer
      - pip3 install junit-xml
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
      - mkdir -p build/allTests
      - |
        if [[ -z "${CONFIG_SOURCE_BUCKET}" ]]; then
          echo 'Pulling config files from Amplify'
          JAVA_HOME=$JDK_8_HOME ./gradlew pullBackendConfigFromAmplify
        else
          echo 'Pulling config files from S3'
          ./scripts/pull_backend_config_from_s3 ${CONFIG_SOURCE_BUCKET}
        fi
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting.'
      - JAVA_HOME=$JDK_8_HOME ./gradlew assembleAndroidTest
      - JAVA_HOME=$JDK_8_HOME ./gradlew runTestsInDeviceFarm
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
      - mkdir -p build/reports/instrumented
      - xunit-viewer -r build/allTests -o build/reports/instrumented/${CODEBUILD_RESOLVED_SOURCE_VERSION}.html
    finally:
      - echo 'Post-build phase completed.'
reports:
  amplify-android-devicefarm-tests:
    files:
      - '**/*'
    base-directory: 'build/allTests'
    discard-paths: no
    file-format: JUNITXML
artifacts:
  files:
    - '**/*.apk'
  name: AmplifyAndroidCatApks
  discard-paths: yes
  secondary-artifacts:
    reports:
      files:
        - '**/*'
      name: DevicefarmTestRunReport
      base-directory: 'build/reports/instrumented'
      discard-paths: no