version: 0.2
# This file is used as part of the build process implemented using AWS CodeBuild [1].
# The CodeBuild documentation [2] provides an introduction of the service and its capabilities. In general
# terms, it allows us to configure the actions executed when a build is triggered by a commit to the
# amplify-android GitHub repository.
#
# For the purposes of this repo, we're simply running a build by using "./gradlew build"
# command and in the post-build phase, we consolidate the JUnit report files in one location.
# In the reports section, we're instructing CodeBuild to publish those reports which can be
# viewed in the AWS CodeBuild console (Future work will be to publish those to Github for easier access).
#
# [1] - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# [2] - https://docs.aws.amazon.com/codebuild/latest/userguide/planning.html
env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      android: 29
      nodejs: 12
    commands:
      - echo 'Install phase starting'
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting.'
      - JAVA_HOME=$JDK_8_HOME ./gradlew build
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
      - pwd
      - mkdir -p build/allTests
      - cp -f ./*/build/test-results/testDebugUnitTest/*.xml ./build/allTests
    finally:
      - echo 'Post-build phase completed.'
reports:
  amplify-android-unit-tests:
    files:
      - build/allTests/*
    discard-paths: yes
    file-format: JUNITXML
