#!/bin/bash

base_dir=`pwd`
dest_dir="$HOME/.aws-amplify/amplify-android"
project_name=$1
module_name=$2
echo "base_dir=$base_dir"
echo "Starting project $project_name"
tmp_amplify_dir="$dest_dir/$project_name"

echo "Removing $tmp_amplify_dir"
rm -rf $tmp_amplify_dir

echo "Creating $tmp_amplify_dir"
mkdir -p $tmp_amplify_dir

cd $tmp_amplify_dir
res_dir="$base_dir/$module_name/src/androidTest/res/raw"
echo "Resource directory for $module_name: $res_dir"

app_id=`aws amplify list-apps --query "apps[?name=='$project_name'].appId" --output text`
echo "Amplify app_id=$app_id"
amplify pull \
  --amplify "{\"projectName\":\"$project_name\",\"appId\":\"$app_id\",\"envName\":\"main\",\"defaultEditor\":\"code\"}" \
  --frontend "{\"frontend\":\"android\",\"config\":{\"ResDir\":\"config_files\"}}" \
  --providers "{\"awscloudformation\":{\"configLevel\":\"general\",\"useProfile\":false,\"region\":\"us-east-1\"}}" \
  --yes
echo "Current dir is $(pwd)"
mkdir -p $res_dir
for config_file in "$tmp_amplify_dir/config_files/raw"/*
do
  filename="$(basename "$config_file")"
  ln -s "$config_file" "$res_dir/$filename"
done
ls -al $res_dir
cd $base_dir
echo "Completed project $project_name"
