#!/bin/bash

set -x
set -e

# This bucket contains a collection of config files that are used by the
# integration tests. The configuration files contain sensitive
# tokens/credentials/identifiers, so are not published publicly.
readonly config_bucket=$1

readonly config_files=(
    # Core
    "core/src/androidTest/res/raw/amplifyconfiguration.json"

    # Analytics
    "aws-analytics-pinpoint/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-analytics-pinpoint/src/androidTest/res/raw/awsconfiguration.json"
    "aws-analytics-pinpoint/src/androidTest/res/raw/credentials.json"

    # API
    "aws-api/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-api/src/androidTest/res/raw/awsconfiguration.json"
    "aws-api/src/androidTest/res/raw/credentials.json"
    "aws-api/src/androidTest/res/raw/amplifyconfigurationlazy.json"

    # DataStore
    "aws-datastore/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-datastore/src/androidTest/res/raw/awsconfiguration.json"
    "aws-datastore/src/androidTest/res/raw/credentials.json"
    "aws-datastore/src/androidTest/res/raw/google_client_creds.json"
    "aws-datastore/src/androidTest/res/raw/amplifyconfigurationupdated.json"

    # DataStore V2
    "aws-datastore/src/androidTest/res/raw/amplifyconfiguration_v2.json"

    # Predictions
    "aws-predictions/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-predictions/src/androidTest/res/raw/awsconfiguration.json"

    # Storage
    "aws-storage-s3/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-storage-s3/src/androidTest/res/raw/awsconfiguration.json"
    "aws-storage-s3/src/androidTest/res/raw/credentials.json"

    # Geo
    "aws-geo-location/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-geo-location/src/androidTest/res/raw/awsconfiguration.json"
    "aws-geo-location/src/androidTest/res/raw/credentials.json"

    # Maplibre Adapter
    "maplibre-adapter/src/androidTest/res/raw/amplifyconfiguration.json"
    "maplibre-adapter/src/androidTest/res/raw/awsconfiguration.json"
    "maplibre-adapter/src/androidTest/res/raw/credentials.json"

    # Auth
    "aws-auth-cognito/src/androidTest/res/raw/amplifyconfiguration.json"
    "aws-auth-cognito/src/androidTest/res/raw/amplifyconfiguration_totp.json"
    "aws-auth-cognito/src/androidTest/res/raw/awsconfiguration.json"
    "aws-auth-cognito/src/androidTest/res/raw/credentials.json"
)

# Set up output path
declare -r dest_dir=$HOME/.aws-amplify/amplify-android
mkdir -p "$dest_dir"

# Download remote files into a local directory outside of the project.
for config_file in ${config_files[@]}; do
    aws s3 cp "s3://$config_bucket/$config_file" "$dest_dir/$config_file" &
done
wait

# Create a symlink for each configuration file.
for config_file in ${config_files[@]}; do
    mkdir -p "$(dirname "$config_file")"
    ln -s "$dest_dir/$config_file" "$config_file" &
done
wait
