theme: jekyll-theme-leap-day
title: AWS Amplify for Android
description: Fresh take on the Android SDK.
url: "https://github.com/awslabs/aws-amplify-android"

github:
  repository_url: "https://github.com/awslabs/aws-amplify-android/tree/master/docs"

show_downloads: true
github.zip_url: "./aws-amplify-android.zip"

exclude:
  README.md

sdk_version: 1.0.0