name: Run code coverage

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run test and generate kover report
        run: ./gradlew koverXmlReport

      - name: Upload Test Report
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          name: report
          files: build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: test-reports
          path: '**/reports/tests/**'
          retention-days: 7
