name: Run code coverage

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Setup Java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run test and generate kover report
        run: ./gradlew koverXmlReport

      - name: Upload Test Report
        uses: codecov/codecov-action@v5
        with:
          name: report
          files: build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: test-reports
          path: '**/reports/tests/**'
          retention-days: 7
