name: "Close stale issues and PRs"

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 200
        stale-issue-message: "This issue is stale since it's been open 30 days with no activity. This will be closed in 7 days unless the `Closing Soon` label is removed or a comment is added. Thank you for your contributions."
        close-issue-message: "This issue was closed since it's been 7 days with no activity."
        days-before-stale: 30
        days-before-close: 7
        # PRs wont go stale
        days-before-pr-stale: -1
        # Only issues and PRs with ALL these labels are checked.
        only-labels: "Clarification Needed"
        # label added after 30 days IF ALL only-labels are present
        stale-issue-label: "Closing Soon"
