name: "Close stale issues"

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@a20b814fb01b71def3bd6f56e7494d667ddf28da # v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 200
        stale-issue-message: "This issue is stale since it's been open 30 days with no activity. This will be closed in 7 days unless the `Closing Soon` label is removed or a comment is added. Thank you for your contributions."
        close-issue-message: "This issue was closed since it's been 7 days with no activity."
        stale-issue-label: "closing soon"
        debug-only: true
        days-before-stale: 30
        days-before-close: 7
        # PRs wont go stale
        days-before-pr-stale: -1
        # Issues with any of these labels are checked.
        any-of-labels: "pending-response, closing soon"
